import uuid
from typing import Protocol

from src.modules.prestadores.domain.entities.contacto_prestador import ContactoPrestador


class ContactoRepository(Protocol):
    """Puerto de persistencia para contactos de PST."""

    async def get_by_id(self, contacto_id: uuid.UUID) -> ContactoPrestador | None: ...
    async def list_by_prestador(self, prestador_id: uuid.UUID) -> list[ContactoPrestador]: ...
    async def list_by_prestadores(
        self, prestador_ids: list[uuid.UUID]
    ) -> dict[uuid.UUID, list[ContactoPrestador]]: ...
    async def add(self, contacto: ContactoPrestador) -> None: ...
    async def save(self, contacto: ContactoPrestador) -> None: ...
    async def delete(self, contacto_id: uuid.UUID) -> None: ...
