import uuid
from typing import Protocol

from src.modules.prestadores.domain.entities.prestador import Prestador


class PrestadorRepository(Protocol):
    """Puerto de persistencia para prestadores."""

    async def get_by_id(self, prestador_id: uuid.UUID) -> Prestador | None: ...
    async def get_by_siges_empresa_id(self, siges_empresa_id: int) -> Prestador | None: ...
    async def list_all(self, *, include_inactive: bool = False) -> list[Prestador]: ...
    async def add(self, prestador: Prestador) -> None: ...
    async def save(self, prestador: Prestador) -> None: ...
