import uuid
from typing import Protocol

from src.modules.auth.domain.entities.user import User
from src.modules.auth.domain.value_objects.email import Email


class UserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def get_by_email(self, email: Email) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def save(self, user: User) -> None: ...
