import uuid
from typing import Protocol

from src.modules.vacaciones.domain.entities.cargo import Cargo
from src.modules.vacaciones.domain.entities.sector import Sector


class SectorRepository(Protocol):
    """Opera sobre la tabla `department` compartida con auth (D1)."""

    async def list_all(self) -> list[Sector]: ...

    async def get_by_id(self, sector_id: uuid.UUID) -> Sector | None: ...

    async def get_by_name(self, name: str) -> Sector | None: ...

    async def add(self, sector: Sector) -> None: ...

    async def save(self, sector: Sector) -> None: ...

    async def delete(self, sector_id: uuid.UUID) -> None: ...


class CargoRepository(Protocol):
    async def list_all(self) -> list[Cargo]: ...

    async def get_by_id(self, cargo_id: uuid.UUID) -> Cargo | None: ...

    async def get_by_name(self, name: str) -> Cargo | None: ...

    async def count_empleados(self, cargo_id: uuid.UUID) -> int: ...

    async def add(self, cargo: Cargo) -> None: ...

    async def save(self, cargo: Cargo) -> None: ...

    async def delete(self, cargo_id: uuid.UUID) -> None: ...
