import uuid
from typing import Protocol

from src.modules.vacaciones.domain.entities.ciclo import Ciclo


class CicloRepository(Protocol):
    async def get(self, empleado_id: uuid.UUID, year: int) -> Ciclo | None: ...

    async def list_por_empleado(self, empleado_id: uuid.UUID) -> list[Ciclo]: ...

    async def list_por_empleados(self, empleado_ids: list[uuid.UUID]) -> list[Ciclo]: ...

    async def list_por_year(self, year: int) -> list[Ciclo]: ...

    async def add(self, ciclo: Ciclo) -> None: ...

    async def save(self, ciclo: Ciclo) -> None: ...
