import uuid
from typing import Protocol

from src.modules.turnos.domain.entities.casilla import Casilla


class CasillaRepository(Protocol):
    """Puerto de persistencia para casillas de turnos."""

    async def get_by_id(self, casilla_id: uuid.UUID) -> Casilla | None: ...
    async def get_by_nombre(self, nombre: str) -> Casilla | None:
        """Búsqueda exacta (mismo criterio que el unique de `turno_casilla.nombre`)."""
        ...

    async def list_all(self, *, include_inactive: bool = False) -> list[Casilla]: ...
    async def add(self, casilla: Casilla) -> None: ...
    async def save(self, casilla: Casilla) -> None: ...
    async def delete(self, casilla_id: uuid.UUID) -> None: ...
