import uuid
from typing import Protocol

from src.modules.turnos.domain.entities.slot import Slot


class SlotRepository(Protocol):
    """Puerto de persistencia para slots de horarios en casillas."""

    async def get_by_id(self, slot_id: uuid.UUID) -> Slot | None: ...
    async def list_by_casilla(self, casilla_id: uuid.UUID) -> list[Slot]: ...
    async def list_all(self) -> list[Slot]: ...
    async def add(self, slot: Slot) -> None: ...
    async def save(self, slot: Slot) -> None: ...
    async def delete(self, slot_id: uuid.UUID) -> None: ...
