"""auth schema

Revision ID: 8bbf8b4979e6
Revises: c033df3b2d32
Create Date: 2026-08-06 11:51:33.450084

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8bbf8b4979e6"
down_revision: str | None = "c033df3b2d32"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.CheckConstraint("key ~ '^[a-z][a-z0-9-]{1,39}$'", name="ck_action_key_format"),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "app_user",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_superadmin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "department",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "login_attempt",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_login_attempt_email_time",
        "login_attempt",
        ["email", sa.literal_column("attempted_at DESC")],
        unique=False,
    )
    op.create_table(
        "module",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("route", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("100"), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("key ~ '^[a-z][a-z0-9-]{1,39}$'", name="ck_module_key_format"),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "module_action",
        sa.Column("module_key", sa.String(), nullable=False),
        sa.Column("action_key", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_key"], ["action.key"], onupdate="CASCADE", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["module_key"], ["module.key"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("module_key", "action_key"),
    )
    op.create_table(
        "password_reset_token",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "permission_audit",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("target_user_id", sa.UUID(), nullable=False),
        sa.Column("module_key", sa.String(), nullable=False),
        sa.Column("action_key", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operation IN ('grant', 'revoke')", name="ck_permission_audit_operation"
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_permission_audit_target",
        "permission_audit",
        ["target_user_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_table(
        "user_module_scope",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("module_key", sa.String(), nullable=False),
        sa.Column("scope_department_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["module_key"], ["module.key"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["scope_department_id"], ["department.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "module_key"),
    )
    op.create_table(
        "user_session",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_user_session_active",
        "user_session",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index("ix_user_session_expires", "user_session", ["expires_at"], unique=False)
    op.create_table(
        "permission_grant",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("module_key", sa.String(), nullable=False),
        sa.Column("action_key", sa.String(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["granted_by"], ["app_user.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["module_key", "action_key"],
            ["module_action.module_key", "module_action.action_key"],
            name="fk_permission_grant_module_action",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "module_key", "action_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permission_grant")
    op.drop_index("ix_user_session_expires", table_name="user_session")
    op.drop_index(
        "ix_user_session_active",
        table_name="user_session",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("user_session")
    op.drop_table("user_module_scope")
    op.drop_index("ix_permission_audit_target", table_name="permission_audit")
    op.drop_table("permission_audit")
    op.drop_table("password_reset_token")
    op.drop_table("module_action")
    op.drop_table("module")
    op.drop_index("ix_login_attempt_email_time", table_name="login_attempt")
    op.drop_table("login_attempt")
    op.drop_table("department")
    op.drop_table("app_user")
    op.drop_table("action")
    # ### end Alembic commands ###
