"""contadores calendario local storage

Revision ID: e2ed69fda1ec
Revises: ebe03bf01e96
Create Date: 2026-08-11 13:18:27.357084

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import insert as pg_insert

revision: str = "e2ed69fda1ec"
down_revision: str | None = "ebe03bf01e96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# "manage" ya existe en el catálogo global de acciones (seed_catalog) — solo
# falta el par (module_key, action_key) para habilitarlo en contadores. Lo
# usa el sync del Calendario (mutación + llamadas externas a Gestión), a
# diferencia de "view" (lectura) y "export" (CSV/DB3).
_module_action = sa.table(
    "module_action", sa.column("module_key", sa.String), sa.column("action_key", sa.String)
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contadores_calendar_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("gestion_event_id", sa.String(), nullable=False),
        sa.Column("operador_id", sa.String(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("start", sa.String(), nullable=False),
        sa.Column("all_day", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("background_color", sa.String(), nullable=True),
        sa.Column("border_color", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("tittle_tooltip", sa.String(), nullable=True),
        sa.Column("content_tooltip", sa.Text(), nullable=True),
        sa.Column("string_tipo_evento", sa.String(), nullable=True),
        sa.Column("cliente", sa.String(), nullable=True),
        sa.Column("vendedor", sa.String(), nullable=True),
        sa.Column("fecha_entrega", sa.String(), nullable=True),
        sa.Column("fecha_entrega_deseada", sa.String(), nullable=True),
        sa.Column("sucursal_entrega", sa.String(), nullable=True),
        sa.Column("sucursal_instalacion", sa.String(), nullable=True),
        sa.Column("sucursal_despacho", sa.String(), nullable=True),
        sa.Column("contacto_entrega", sa.String(), nullable=True),
        sa.Column("contacto_instalacion", sa.String(), nullable=True),
        sa.Column("bultos", sa.Float(), nullable=True),
        sa.Column("costo_seguro", sa.String(), nullable=True),
        sa.Column("costo_recambio", sa.String(), nullable=True),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "gestion_event_id", "operador_id", name="uq_calendar_event_gestion_operador"
        ),
    )
    op.create_index(
        "ix_calendar_event_date", "contadores_calendar_events", ["event_date"], unique=False
    )
    op.create_table(
        "contadores_operadores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    bind = op.get_bind()
    bind.execute(
        pg_insert(_module_action).on_conflict_do_nothing(
            index_elements=["module_key", "action_key"]
        ),
        [{"module_key": "contadores", "action_key": "manage"}],
    )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(
        _module_action.delete().where(
            _module_action.c.module_key == "contadores",
            _module_action.c.action_key == "manage",
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contadores_operadores")
    op.drop_index("ix_calendar_event_date", table_name="contadores_calendar_events")
    op.drop_table("contadores_calendar_events")
    # ### end Alembic commands ###
