"""contadores schema

Revision ID: fc502aa52749
Revises: d5142d7dc6fb
Create Date: 2026-08-07 10:00:20.774304

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fc502aa52749'
down_revision: str | None = 'd5142d7dc6fb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ftp_clients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('path', sa.String(), server_default=sa.text("'/'"), nullable=False),
    sa.Column(
        'pattern', sa.String(),
        server_default=sa.text("'PrinterMonitorClient.db3.*'"), nullable=False,
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meter_client_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('suma_color', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False,
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'customer_id', name='uq_meter_client_source_customer')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meter_client_configs')
    op.drop_table('ftp_clients')
    # ### end Alembic commands ###
