import uuid
from typing import Protocol

from src.modules.contadores.domain.entities.cliente_nuevo import ClienteNuevo


class ClienteNuevoRepository(Protocol):
    async def get_by_id(self, ficha_id: uuid.UUID) -> ClienteNuevo | None: ...
    async def get_abierta_by_cliente(self, cliente: str) -> ClienteNuevo | None: ...
    async def list_all(self) -> list[ClienteNuevo]: ...
    async def list_siges_empresa_ids(self) -> set[int]: ...
    async def add(self, ficha: ClienteNuevo) -> None: ...
    async def save(self, ficha: ClienteNuevo) -> None: ...
    async def delete(self, ficha_id: uuid.UUID) -> None: ...
