import uuid
from typing import Protocol

from src.modules.contadores.domain.entities.ftp_client import FtpClient


class FtpClientRepository(Protocol):
    async def get_by_id(self, client_id: uuid.UUID) -> FtpClient | None: ...
    async def get_by_name(self, name: str) -> FtpClient | None: ...
    async def list_all(self) -> list[FtpClient]: ...
    async def add(self, client: FtpClient) -> None: ...
    async def save(self, client: FtpClient) -> None: ...
    async def delete(self, client_id: uuid.UUID) -> None: ...
